blog/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
from django.contrib import admin

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    #/blog/

    url(r'^(?P<auth_user_id>[0-9]+)', views.detail, name='detail'),
    # /blog/0-9/

    url(r'^login/', auth_views.login, name='login'),
    #/blog/login.

    url(r'^logout/', auth_views.logout, {'next_page': '/blog/'}, name='logout'),
    #blog/login, after logout it redirects back to the loginpage.

    url(r'^profile/(?P<auth_user_id>[0-9]+)', views.UserProfile, name='profile'),
    #/detail

    url(r'^admin/', admin.site.urls),

    url(r'^posts-add/(?P<auth_user_id>[0-9]+)', views.get_name, name='posts-add'),

    url(r'^change_profile/(?P<auth_user_id>[0-9]+)', views.change_profile, name='change_profile'),


]

home/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
from django.contrib import admin

app_name = 'home'

urlpatterns = [

]

rfs/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from home import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
    url(r'^detail/',include('blog.urls')),
    url(r'^thanks/',include('blog.urls')),
    url(r'^home/',include('home.urls')),
    url(r'^$', views.home, name='home')





]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

class Posts( models.Model):
    auth_user = models.ForeignKey(User, on_delete=models.CASCADE,)
    title = models.CharField(max_length=50)
    blog_post = models.TextField()
    time_date = models.DateTimeField()
    blog_pic = models.CharField(max_length=1000)

    def __str__(self):
        return self.title

class Profile (models.Model):
    auth_user = models.ForeignKey(User, on_delete=models.CASCADE,)
    profile_info = models.TextField(max_length=2500)
    profile_pic = models.CharField(max_length=1000)

    def __str__(self):
        return self.profile_info

home/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Posts, Profile
from ckeditor.widgets import CKEditorWidget

from django import forms

class PostsAdd(forms.Form):
    titel = forms.CharField(label='Titel', max_length=100)
    blog_post = forms.CharField(label='', widget=CKEditorWidget())

class ProfileChange(forms.Form):
    profile_pic = forms.CharField(label='', max_length=100)
    profile_info = forms.CharField(label='', widget=CKEditorWidget())



blog/views.py
from .models import Posts, Profile
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import logout
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import PostsAdd, ProfileChange
import datetime

#from .forms import NameForm

#shows users on the blog
def index(request):
    all_posts = User.objects.filter()
    return render(request, 'blog/index.html', {'all_posts': all_posts})

#shows all posts and filter it by users url.
def detail(request, auth_user_id):

    user = auth_user_id

    all_posts = Posts.objects.order_by('-time_date')
    all_posts = all_posts.filter(auth_user_id=user)

    profile_info = Profile.objects.all()
    profile_info = profile_info.filter(auth_user_id=user)

    matrix = [profile_info], [all_posts]

    return render(request, 'blog/detail.html', {'all_posts': all_posts, 'profile': profile_info})

def UserProfile(request,auth_user_id):

    profile_info = Profile.objects.all()
    user = auth_user_id
    profile_info = profile_info.filter(auth_user_id=user)
    return render(request, 'blog/profile.html', {'profile_info': profile_info})

def logout_view(request):
    logout(request)
    return HttpResponse('registration/login.html')


def get_name(request, auth_user_id):

    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = PostsAdd(request.POST)
        print(request.POST['titel'])
        print(request.POST['blog_post'])
        p = Posts(auth_user_id=auth_user_id, title=request.POST['titel'], blog_post=request.POST['blog_post'], time_date=datetime.datetime.now(), blog_pic="")
        p.save()
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/thanks/' + auth_user_id)

    # if a GET (or any other method) we'll create a blank form
    else:
        form = PostsAdd()

    return render(request, 'blog/posts-add.html', {'form': form, 'id': auth_user_id})

def change_profile(request, auth_user_id):

    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ProfileChange(request.POST)
        print(request.POST['profile_pic'])
        print(request.POST['profile_info'])
        p = Profile(auth_user_id=auth_user_id, profile_pic=request.POST['profile_pic'], profile_info=request.POST['profile_info'])
        p._do_update(pk_val=auth_user_id, update_fields=['profile_pic' 'profile_info'])
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/thanks/' + auth_user_id)

    # if a GET (or any other method) we'll create a blank form
    else:
        form = ProfileChange()

    return render(request, 'blog/change_profile.html', {'form': form, 'id': auth_user_id})






























































home/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home/parallaxIndex.html')

blog/templates/blog/change_profile.html
{% include "blog/includes/html_template.html" %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'blog/style.css' %}" type='text/css'/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">


{% if user.is_authenticated %}
{% include "blog/includes/navbar.html" %}
{% endif %}

<div class="add_posts">
    <div class="container">
    <div class="row">
    <div class="col-m-4"></div>
    <div id="form-row" class="col-m-4">
        <h1>Add picture URL and write your profile info here </h1>

        <form class="form-row" action="" method="POST">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}



        <input type="submit" value="Submit" />

        </form>

    <div class="col-m-4"></div>
        </div>

    </div>
    </div>

blog/templates/blog/detail.html
{% include "blog/includes/html_template.html" %}
  <title>RFS</title>
  {% load staticfiles %}
<link rel="stylesheet" href="{% static 'blog/style.css' %}" type='text/css'/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
</head>



   {% if user.is_authenticated %}

    {% else %}
    {% include "blog/includes/navbar_guest.html" %}
    {% endif %}

{% include "blog/includes/navbar.html" %}
{% include "blog/includes/blog_posts.html" %}


blog/templates/blog/includes/all_blogs.html


{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'blog/style.css' %}" type='text/css'/>
<link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">

{% block content %}

    {% if user.is_authenticated %}

    {% else %}
    {% include "blog/includes/navbar_guest.html" %}
    {% endif %}

{% if all_posts %}


{% for post in all_posts|slice:"1:" %}
    <div class="all_posts">
    <div class="container">
        <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4"><a  href=" {% url 'blog:detail' post.id %}" class="list-group-item"> {{ post.username }}</a></div>
        <div class="col-sm-4"></div>
        </div>
    </div>
    </div>
{% endfor %}


{% else %}
    <h3>Null</h3>
{% endif %}

{% endblock %}


blog/templates/blog/includes/blog_posts.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static '/blog/style.css' %}" type='text/css'/>
<link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

{% block content %}

    {% if all_posts %}
{% for user in all_posts|slice:":1:" %}
    <div><h1 class="user_name">{{ user.auth_user }}'s blog!</h1></div>

    {% endfor %}

{% for info in profile %}
<div class="profile_info">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 test" ><img class="profile_pic" src="{{ info.profile_pic }}"><br><div class="profile_info_info">{{ info.profile_info }}</div></div>
            <div class="col-sm-6">
            {% for post in all_posts %}

                    <h1 id="title">{{ post.title }}</h1>
                    <h2 id="blog_post">{{ post.blog_post|safe }}</h2>
                    <h6>{{ post.time_date }}</h6><hr>

            {% endfor %}
        </div>
        </div>
    </div>
</div>
{% endfor %}



{% else %}
        <div class="no_post">No posts found, try again later!</div>
{% endif %}

{% endblock %}


blog/templates/blog/includes/html_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Rfs</title>
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'blog/style.css' %}" type='text/css'/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>

</body>
</html>

blog/templates/blog/includes/navbar.html
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'blog/style.css' %}" type='text/css'/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
{% block content %}


{% if user.is_authenticated %}

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}"><img class="brand" alt="Brand" src="{% static 'blog/images/Logga_svart.png' %}">
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'blog:index' %}">Home</a></li>
        <li><a href="/blog/profile/{{ user.id }}" >Profile</a></li>
        <li><a href="/blog/posts-add/{{ user.id }}">New blogpost</a></li>
        <li><a href="{% url 'blog:logout' %}">Log out</a></li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group"></div>
      </form>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->

</nav>



{% else %}
    {% endif %}


{% endblock %}

blog/templates/blog/includes/navbar_guest.html
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'blog/style.css' %}" type='text/css'/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">

{% block content %}


<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'blog:index' %}"><img class="brand" alt="Brand" src="{% static 'blog/images/Logga_svart.png' %}">
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'blog:index' %}">Home</a></li>


        <li><a href="{% url 'blog:login' %}">Log in</a></li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group"></div>
      </form>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->

</nav>


{% endblock %}

blog/templates/blog/index.html
{% include "blog/includes/html_template.html" %}

<!-- loads the path to your static files -->
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'blog/style.css' %}</div>" type='text/css'/>
<link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">





{% include "blog/includes/navbar.html" %}
{% include "blog/includes/all_blogs.html" %}


blog/templates/blog/posts-add.html
{% include "blog/includes/html_template.html" %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'blog/style.css' %}" type='text/css'/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">


{% if user.is_authenticated %}
{% include "blog/includes/navbar.html" %}
{% endif %}

<div class="add_posts">
    <div class="container">
    <div class="row">
    <div class="col-m-4"></div>
    <div id="form-row add" class="col-m-4">
        <h1>Add title and write your blogpost</h1>

        <form class="form-row" action="" method="post">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}



        <input type="submit" value="Submit" />

        </form>

    <div class="col-m-4"></div>
        </div>

    </div>
    </div>

blog/templates/blog/profile.html
{% include "blog/includes/html_template.html" %}
  {% load staticfiles %}
<link rel="stylesheet" href="{% static 'blog/style.css' %}" type='text/css'/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">





  {% if user.is_authenticated %}
    {% include "blog/includes/navbar.html" %}
{% endif %}
<div class="user_name">
    <div class="container">
        <div class="row">
            <div class="col-sm-4"></div>
            <div class="col-sm-4"><h1 class="font">{{ user.first_name }} {{ user.last_name }}</h1></div>
            <div class="col-sm-4"></div>
        </div>
    </div>
</div>


{% for info in profile_info|slice:":1"  %}

<div class="profile_info">
    <div class="container">
        <div class="row">
            <div class="col-sm-4"></div>
            <div class="col-sm-4"><img class="profile_pic" src="{{ info.profile_pic }}"><div class="profile_info_info">{{ info.profile_info }}</div></div>
            <div class="col-sm-4"></div>
        </div>
    </div>
</div>


    <button><li><a href="#">New blogpost</a></li></button>
{% endfor %}

home/templates/home/parallaxIndex.html
<!DOCTYPE html>
<html lang="sv">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>Recycling Fashion SHOW</title>
{% load staticfiles %}
  <link rel=“stylesheet” href=“https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css” integrity=“sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u” crossorigin=“anonymous”>
  <link rel="stylesheet" href="{% static 'blog/bootstrap.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'blog/parallaxStyle.css' %}" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
  <script src="https://use.fontawesome.com/2bad560e67.js"></script>

</head>

      <body>
        <!-- <div class="container"> -->
          <!-- starter -->
          <section class="parallax">
            <div class="row header">
              <div class="container">
                <img id="logo" src="{% static 'blog/images/img/logga_vit.png'%}" alt="">
                <img src="{% static 'blog/images/img/start/tjej_bubbla.png' %}" id="start_girl">

                  <!-- navbar -->
     <div class="container">
       <ul class="topnav">
         <li class="nav-item">
           <a class="nav-link" href="#about"><img src="img/about.png" id="nav_icon" alt="Om oss"></a>
         </li>
         <li class="nav-item">
           <a class="nav-link" href="{% url 'blog:index' %}"><img src="img/blogg.png" id="nav_icon" alt="Blogg"></a>
         </li>
         <li class="nav-item">
           <a class="nav-link" href="#lookbook"><img src="img/Lookbook.png" id="nav_icon" alt="Lookbook"></a>
         </li>
         <li class="nav-item">
           <a class="nav-link" href="#form"> <img src="img/form.png" id="nav_icon" alt="Formulär"></a>
         </li>
         <li class="nav-item">
           <a class="nav-link" href="#faq"> <img src="img/faq.png" id="nav_icon" alt="Faq"></a>
         </li>
         <li class="nav-item">
           <a class="nav-link" href="#contact"> <img src="img/kontakt.png" id="nav_icon" alt="kontakt"></a>
         </li>
       </ul>
     </div>
   </div>
   <!-- end navbar -->

              </div>
            </div>
          </section>
            <!-- end starter -->
            <!-- om oss -->
          <section class="parallax2">
            <div class="row" id="about">
              <div class="container">
                  <img src="{% static 'blog/images/img/about/about_girl.png'%}" id="about_girl">
              </div>
            </div>
          </section>
            <!-- end om oss -->
            <!-- lookbook -->
          <section class="parallax3">
            <div class="row" id="lookbook">
              <div class="container">
                  <img src="{% static 'blog/images/img/lookbook/lookbook_modell.png'%}" id="lookbook_girl">
                  <img src="{% static 'blog/images/img/button/button_left.png'%}" id="arrow_l">
                  <img src="{% static 'blog/images/img/lookbook/lookbook.png'%}" id="lookbook_book">
                  <img src="{% static 'blog/images/img/button/button_right.png'%}" id="arrow_r">
                  <img src="{% static 'blog/images/img/lookbook/lookbook_boxes.png'%}" id="boxes">
              </div>
            </div>
          </section>
            <!-- end lookbook -->
            <!-- formulär -->
          <section class="parallax4">
            <div class="row" id="form">
              <div class="container">
                  <img src="{% static 'blog/images/img/form/form_modell.png'%}" id="form_girl">
              </div>
            </div>
          </section>
          <!-- end formulär -->
          <!-- faq -->
          <section class="parallax5">
            <div class="row" id="faq">
              <div class="container">
                  <img src="{% static 'blog/images/img/faq/faq_modell.png'%}" id="faq_girl">
              </div>
            </div>
          </section>
          <!-- end faq -->
          <!-- kontakt -->
          <section class="parallax6">
            <div class="row" id="contact">
              <div class="container">
                <img src="{% static 'blog/images/img/kontakt/kontakt_modell.png'%}" id="kontakt_girl">
              </div>
            </div>
          </section>
          <!-- end kontakt -->
          <!-- footer -->
          <div id="footer">
              <h2>
                Copyright <i class="fa fa-copyright" aria-hidden="true"></i>  Live Green 2017. developd by room 211
              </h2>
          </div>
          <!-- end footer -->
      </div>
          <!-- include javascript, jQuery FIRST -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="js/bootstrap.min.js"></script>

      </body>

      </html>